apiVersion: v1
kind: ReplicationController
metadata:
  creationTimestamp: null
  labels:
    operator.synopsys.com/group-id: "AlertRC"
    operator.synopsys.com/group-dependencies: "ConfigMap_AlertSecret"
    app: alert
    component: alert
    name: demo
  name: demo-alert-alert
  namespace: default
spec:
  replicas: 1
  selector:
    app: alert
    component: alert
    name: demo
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: alert
        component: alert
        name: demo
      name: demo-alert-alert
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: demo-alert-blackduck-config
            - secretRef:
                name: demo-alert-secret
          image: docker.io/blackducksoftware/blackduck-alert:4.0.0
          imagePullPolicy: Always
          livenessProbe:
            exec:
              command:
                - /usr/local/bin/docker-healthcheck.sh
                - https://localhost:8443/alert/api/about
            failureThreshold: 5
            initialDelaySeconds: 240
            periodSeconds: 30
            timeoutSeconds: 10
          name: alert
          ports:
            - containerPort: 8443
              protocol: TCP
          resources:
            limits:
              memory: 2560M
            requests:
              memory: 2560M
          volumeMounts:
            - mountPath: /opt/blackduck/alert/alert-config
              name: dir-alert
      dnsPolicy: ClusterFirst
      volumes:
        - name: dir-alert
          persistentVolumeClaim:
            claimName: demo-alert-alert-pvc
status:
  replicas: 0

---
apiVersion: v1
kind: ReplicationController
metadata:
  creationTimestamp: null
  labels:
    operator.synopsys.com/group-id: "CfsslRC"
    operator.synopsys.com/group-dependencies: "ConfigMap"
    app: alert
    component: cfssl
    name: demo
  name: demo-alert-cfssl
  namespace: default
spec:
  replicas: 1
  selector:
    app: alert
    component: cfssl
    name: demo
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: alert
        component: cfssl
        name: demo
      name: demo-alert-cfssl
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: demo-alert-blackduck-config
          image: docker.io/blackducksoftware/blackduck-cfssl:1.0.0
          livenessProbe:
            exec:
              command:
                - /usr/local/bin/docker-healthcheck.sh
                - http://localhost:8888/api/v1/cfssl/scaninfo
            failureThreshold: 10
            initialDelaySeconds: 240
            periodSeconds: 30
            timeoutSeconds: 10
          name: blackduck-cfssl
          ports:
            - containerPort: 8888
              protocol: TCP
          resources:
            limits:
              memory: 640M
            requests:
              memory: 640M
          volumeMounts:
            - mountPath: /etc/cfssl
              name: dir-cfssl
      dnsPolicy: ClusterFirst
      volumes:
        - emptyDir: {}
          name: dir-cfssl
status:
  replicas: 0

---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    operator.synopsys.com/group-id: "AlertRC"
    operator.synopsys.com/group-dependencies: "ConfigMap_AlertSecret"
    app: alert
    component: alert
    name: demo
  name: demo-alert-alert
  namespace: default
spec:
  ports:
    - name: port-8443
      port: 8443
      protocol: TCP
      targetPort: 8443
  selector:
    app: alert
    component: alert
    name: demo
  type: ClusterIP
status:
  loadBalancer: {}

---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    operator.synopsys.com/group-id: "CfsslRC"
    operator.synopsys.com/group-dependencies: "ConfigMap"
    app: alert
    component: cfssl
    name: demo
  name: demo-alert-cfssl
  namespace: default
spec:
  ports:
    - name: port-8888
      port: 8888
      protocol: TCP
      targetPort: 8888
  selector:
    app: alert
    component: cfssl
    name: demo
  type: ClusterIP
status:
  loadBalancer: {}

---
apiVersion: v1
data:
  ALERT_SERVER_PORT: "8443"
  PUBLIC_HUB_WEBSERVER_HOST: localhost
  PUBLIC_HUB_WEBSERVER_PORT: "443"
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    operator.synopsys.com/group-id: "ConfigMap"
    operator.synopsys.com/group-dependencies: ""
    app: alert
    component: alert
    name: demo
  name: demo-alert-blackduck-config
  namespace: default

---
apiVersion: v1
data:
  ALERT_ENCRYPTION_GLOBAL_SALT: ""
  ALERT_ENCRYPTION_PASSWORD: ""
kind: Secret
metadata:
  creationTimestamp: null
  labels:
    operator.synopsys.com/group-id: "AlertSecret"
    operator.synopsys.com/group-dependencies: "ConfigMap"
    app: alert
    component: alert
    name: demo
  name: demo-alert-secret
  namespace: default
type: Opaque

# TODO Routes
# apiVersion: route.openshift.io/v1
# kind: Route
# metadata:
#   annotations:
#     openshift.io/host.generated: "true"
#   creationTimestamp: "2019-08-12T14:50:39Z"
#   labels:
#     app: alert
#     component: route
#     name: demo
#   name: demo-alert
#   namespace: default
#   resourceVersion: "2414"
#   selfLink: /apis/route.openshift.io/v1/namespaces/demo/routes/demo-alert
#   uid: 8d100e5e-bd10-11e9-a198-08002782ac65
# spec:
#   host: demo-alert-demo.192.168.99.100.nip.io
#   port:
#     targetPort: port-8443
#   tls:
#     termination: passthrough
#   to:
#     kind: Service
#     name: demo-alert-alert
#     weight: 100
#   wildcardPolicy: None
# status:
#   ingress:
#     - conditions:
#         - lastTransitionTime: "2019-08-12T14:50:39Z"
#           status: "True"
#           type: Admitted
#       host: demo-alert-demo.192.168.99.100.nip.io
#       routerName: router
#       wildcardPolicy: None
