
[[constraint]]
  name = "github.com/gobuffalo/buffalo"
  version = "v0.13.5"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/blackducksoftware/synopsys-operator"
  branch = "release-2019.4.x"

[[override]]
  name = "k8s.io/api"
  revision = "d216743eed4c3242b85d094d2a589f41a793652d"

[[override]]
  name = "k8s.io/apimachinery"
  revision = "94ebb086c69b9fec4ddbfb6a1433d28ecca9292b"

[[override]]
  name = "k8s.io/kube-aggregator"
  revision = "29c7989121fc30258c674f31aff9bbd393dfab5e"

[[override]]
  name = "k8s.io/apiextensions-apiserver"
  revision = "e798125b68b9e62ce80c2b4f1157e96da7b3b1c7"

[[override]]
  name = "k8s.io/client-go"
  #branch = "master"
  version = "v8.0.0"

# DO NOT DELETE
[[prune.project]] # buffalo
  name = "github.com/gobuffalo/buffalo"
  unused-packages = false

# DO NOT DELETE
[[prune.project]] # pop
  name = "github.com/gobuffalo/pop"
  unused-packages = false
